//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saloonappointment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int Appointment_Id { get; set; }
        public Nullable<int> Client_Id { get; set; }
        public Nullable<int> Service_Id { get; set; }
        public string Start_Time { get; set; }
        public string End_Time { get; set; }
        public string Expected_End_Time { get; set; }
        public Nullable<double> Total_Amount { get; set; }
        public string If_Cancelled { get; set; }
        public string Cancel_Reason { get; set; }
        public string If_Rescheduled { get; set; }
        public Nullable<System.DateTime> Appointment_Date { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
