//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saloonappointment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Booking_Id { get; set; }
        public string Booking_Name { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<System.DateTime> Booking_Date { get; set; }
        public Nullable<double> Advance { get; set; }
        public Nullable<double> Total_Amount { get; set; }
        public Nullable<int> Client_Id { get; set; }
    
        public virtual Booking Booking1 { get; set; }
        public virtual Booking Booking2 { get; set; }
    }
}
