//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saloonappointment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Emp_Id { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_Username { get; set; }
        public string Emp_Email { get; set; }
        public string Emp_Password { get; set; }
        public Nullable<int> Emp_Avalaible_From { get; set; }
        public Nullable<int> Emp_Avalaible_To { get; set; }
        public string Emp_Job_Title { get; set; }
        public string Emp_Address { get; set; }
        public string Emp_Contact_No { get; set; }
        public string Emp_Image { get; set; }
    }
}
