//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saloonappointment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Product_Id { get; set; }
        public string Product_Name { get; set; }
        public Nullable<double> Product_Price { get; set; }
        public string Product_Desc { get; set; }
        public Nullable<System.DateTime> Product_Manufect_Date { get; set; }
        public Nullable<System.DateTime> Product_Expiry_Date { get; set; }
        public Nullable<int> Product_Qty { get; set; }
        public string Product_Benifit { get; set; }
        public Nullable<int> Prod_Category_Id { get; set; }
        public string Product_Img { get; set; }
    
        public virtual Product_Category Product_Category { get; set; }
    }
}
