//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saloonappointment
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string U_Firstname { get; set; }
        public string U_Lastname { get; set; }
        public string U_Email { get; set; }
        public string U_Password { get; set; }
        public string gender { get; set; }
    }
}
